apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: whatever6
  annotations:
    # If your repository has TechDocs content in the root, local builds can use this
    # in Backstage with the TechDocs plugin.
    backstage.io/techdocs-ref: 'dir: .'
    # Optionally trigger the GitHub Actions plugin (if installed).
    # Replace with your own GitHub slug in the entity after registration.
    github.com/project-slug: 'jnmaih/whatever5'
spec:
  type: service
  owner: group:default/team-b
  lifecycle: experimental
